### ISSUE TITLE
Buggy multi-cursor subword deletion

### ISSUE THREAD

**Issue by kumarharsh** [ow--/vscode-subword-navigation#11]
Say I have this code:

```
import GameInput from 'GameInput';
export default GameInput;
```

Now, select the `GameInput` word, and press <kbd>Ctrl+Shift+L</kbd> to select all three occurences. Now move the cursor to the end of each word (by pressing <kbd>--></kbd>). Now, press <kbd>Alt+BackSpace</kbd> to delete the subword `Input`.

What should happen:

```
import Game from 'Game';
export default Game;
```

What happens:
*The word inside the string does not get deleted:
```
import Game from 'GameInput';
export default Game;
```

Additionally, undoing becomes very weird (it undoes only one word at a time, not all three as it should be)

**Comment by ow--** [comment]
Ha. The age-old removing-while-looping conundrum. Sort of. The indexes of selections are thrown off when deleting in the wrong order on the same line of course. I'll get that fixed.

The other issue is secretly known. I didn't find the obvious way of applying the deletes as an atomic edit. I'll dig further in the APIs.

**Comment by ow--** [comment]
Got it. Too used to the tooltip help you get in .NET and grown-up VS to see the obvious way.

Sorry about the delay, you caught me just as I was getting ready for vacation. :sunglasses:
