### ISSUE TITLE
new_line_character is eaten by `cursorSubwordRight.*` commands

### ISSUE THREAD

**Issue by jvlad** [ow--/vscode-subword-navigation#13]
StR:

1. Open new (empty) editor
1. Place cursor at the beginning of a new empty line
    fdfsdf
1. Enter any camel_case word: e. g. `testWord`
1. Make sure there is no space character after `testWord`. Press `Enter` right after last character (`d`) to make one more line below
1. Move cursor to position before capital character: between `t` and `W`
1. Invoke any `cursorSubwordRight.*` command: e. g. "cursorSubwordRight"  

**result:** cursor jumps to the beginning of the next line  
**expected:** cursor goes to the end of the current line, i. e. placed right after `d` character

This behavior also remains while running "cursorSubwordRightSelect" and "deleteSubwordRight" commands.

**Comment by ow--** [comment]
Oh my. I'd really better get on creating that all-covering test suite.

I'll have a fix up when I believe I haven't broke anything else. Thanks.
