### ISSUE TITLE
ctrl+right and ctrl+left is not working

### ISSUE THREAD

**Issue by rubymaniac** [ow--/vscode-subword-navigation#14]
I have added to my `keybindings.json` your quickstart guide but the *subwordNavigation.cursorSubwordLeft* and the *subwordNavigation.cursorSubwordRight* are not working. These combinations are not assigned to anything in the default keybindings file.

**Comment by ow--** [comment]
That's odd. It should just subsume the default function in _Default Keyboard Shortcuts_, and it seems to work for me. Although I personally normally run with `alt+left/right`. Mind posting the contents of your keybindings.json?

**Comment by rubymaniac** [comment]
Yes ofc here it is:

```json
// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "cmd+t",
        "command": "workbench.action.quickOpen"
    },
    {
        "key": "cmd+t",
        "command": "workbench.action.quickOpenNavigateNext",
        "when": "inQuickOpen"
    },
    {
        "key": "cmd+p",
        "command": "workbench.action.showAllSymbols"
    },
    {
        "key": "ctrl+left",
        "command": "subwordNavigation.cursorSubwordLeft",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+right",
        "command": "subwordNavigation.cursorSubwordRight",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+shift+left",
        "command": "subwordNavigation.cursorSubwordLeftSelect",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+shift+right",
        "command": "subwordNavigation.cursorSubwordRightSelect",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+backspace",
        "command": "subwordNavigation.deleteSubwordLeft",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+delete",
        "command": "subwordNavigation.deleteSubwordRight",
        "when": "editorTextFocus"
    }
]
```

**Comment by ow--** [comment]
I don't know man. Guess I'll have to get a hold of a mac. I'll see if there's one not tied up in release testing at work some day.

Actually, @massimocode have you had any issues like this?

**Comment by rubymaniac** [comment]
After I changed it to `alt+left` and `alt+right` and it worked I figured that something else used these combinations for shortcuts. It turns out that in System Preferences -> Keyboard -> Shortcuts  under Mission Control the `ctrl+left` and `ctrl+right` are in use :/

**Comment by ow--** [comment]
Wow. I'd be irked. Leave my code navigation keys alone!

Anyway, good that you found it. :+1:

**Comment by massimocode** [comment]
Sorry to be late to the party... sent my Lumia to MS for fixing so no email notifications! Yes this is because of Mission Control, I had the same issue. Maybe worth adding a line to the readme at some point or defining different shortcuts for Mac (Command left, command right, etc)
