### ISSUE TITLE
Bug with latest VS Code Insiders build

### ISSUE THREAD

**Issue by massimocode** [ow--/vscode-subword-navigation#16]
- VSCode Version: Code - Insiders 1.8.0-insider (d3f14897a3149f5982db31b52ba7edb254466b14, 2016-11-07T07:11:40.337Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.0.8|
|githistory|donjayamanne|0.1.0|
|csharp|ms-vscode|1.4.1|
|PowerShell|ms-vscode|0.7.2|
|typescript-javascript-grammar|ms-vscode|0.0.7|
|vscode-subword-navigation|ow|1.1.5|
|Ruby|rebornix|0.10.1|
|vscode-icons|robertohuertasm|4.0.0|
|annotator|ryu1kn|0.10.1|
|wallaby-vscode|WallabyJs|1.0.30|

---

Steps to Reproduce:

1. Paste the following code into a file
```javascript
expect(something).toBe(true);
```
2. Put the cursor at the end between `true` and `);`
3. Subword delete backwards
4. The word true is deleted but the cursor appears at the end of the line instead of staying where it should be

**Comment by massimocode** [comment]
Let's wait a day or 2 on this before investigating... I'll see if it's just a temporary issue in VS Code Insiders

**Comment by ow--** [comment]
Yea it does not seem to be around in the live version, so let's wait and see what the secret plan to destroy our lives is.

**Comment by ow--** [comment]
I'll close this for now if you don't mind. Just reopen or start anew if it rears its head again.
