### ISSUE TITLE
Doesn't work with TypeScript's Rename Symbol

### ISSUE THREAD

**Issue by appsforartists** [ow--/vscode-subword-navigation#20]
# Steps to Reproduce # 
1. Select a `camelCased` token in a TypeScript file
2. Select **Rename Symbol** from the Command Palette
3. Hit ctrl+left or ctrl+right to navigate to a subword

# Expected Results # 
It works just like it would if I wasn't in the Replace widget.

# Actual Results # 
Nothing if `when: "editorTextFocus"` is set.  Replace widget closes if it is not set.

**Comment by ow--** [comment]
Yeah I know. I wish this was possible, but alas, the the rename widget, and other inputs like search boxes, are as of this writing implemented as a straight up HTMLInputElements. And with, as far as I can tell, no extension points. 

[renameInputField.ts](https://github.com/Microsoft/vscode/blob/d98f5893cd150fb9db555d65f481995361f360d0/src/vs/editor/contrib/rename/browser/renameInputField.ts)

However, I noticed once that whatever is selected when **Rename Symbol** is initiated is pre-selected in the rename widget. So what I have trained myself to do instead is to select the part of the word I want to change before hitting F2 when subword navigation is still possible. It's not optimal, but it's what we've got right now.
