### ISSUE TITLE
Remote experience is really laggy

### ISSUE THREAD

**Issue by ColCh** [ow--/vscode-subword-navigation#34]
This extension seems to be not optimized for remote-ssh mode. I may be wrong though :)

1) After logging into fresh remote installation, vscode can't find commands:
```
command 'subwordNavigation.cursorSubwordLeft' not found
```

2) installing extension in `ssh` (e.g. installs extension on vscode-server side) helps, but it really lags as hell

I think this is because extension is working on server side..

So, is there a way to make it working on client side?

**Comment by ow--** [comment]
Good question. The extension certainly predates remote-ssh and I've never actually tried it or really read up on the extension model for remote. But then I also just assumed everyone but me uses the built-in subword navigation now. Does that not work for you?

**Comment by ColCh** [comment]
Built-in subword navigation? Hm... Please provide a bit more info. I know nothing about built-in subword navigation feature

**Comment by ow--** [comment]
https://code.visualstudio.com/updates/v1_25#_subword-support

**Comment by ColCh** [comment]
Oh my God. I feel stupid. Thank you for the link! Feel free to close this issue :)

**Comment by ow--** [comment]
No worries, happy to help 🙂

It seems to do the trick but it didn't work the same as mine around whitespace between words so I've kept my version around. Mostly for my own sake 😉 But I haven't developed it further since.
