### ISSUE TITLE
Navigation past end of screen

### ISSUE THREAD

**Issue by massimocode** [ow--/vscode-subword-navigation#5]
Hi Olle

First of all I should thank you again for all your hard work creating this extension. It has made my transition from VS2015+ReSharper to VS Code (as I'm now working on a Mac) so much better!

I noticed today that when I navigate through normal scrolling (i.e. right/left arrows) past the end of my screen (i.e. if I have a really long line of code, or several tabs open side-by-side) then the view scrolls with the cursor so I can see what I'm doing. However, using subword navigation the screen does not scroll with my cursor so I can't see the cursor when it goes off the screen.

**Comment by ow--** [comment]
Heh, did not anticipate that one. Especially since that's not the case in big boy VS. At least it was easy to do. I should push this later this evening.
