### ISSUE TITLE
Cursor sometimes doesn't stop on periods

### ISSUE THREAD

**Issue by JustinPierce** [ow--/vscode-subword-navigation#6]
The first thing I tried with this extension was navigating through the key bindings that I just defined. For example, `"command": "subwordNavigation.cursorSubwordRight"`. When navigating through those subwords, however, the cursor doesn't stop at or after the period. As the default cursor navigation _does_ stop at periods, I would guess that the extension isn't behaving as expected.

This doesn't seem to be consistent, however. It's working find in my TypeScript files, for example.

**Comment by ow--** [comment]
Apparently TextDocument.getWordRangeAtPosition doesn't always work the same in all languages. That's a bit annoying for my use case. Guess I'll have to do that myself as well.

Thanks for the find.
