### ISSUE TITLE
Cannot navigate backward to the beginning of the file

### ISSUE THREAD

**Issue by JustinPierce** [ow--/vscode-subword-navigation#7]
When navigating backward (ctrl-left), the extension reports an error when it attempts to place the cursor at what would be the beginning of the file. This only seems to occur when the file starts with word characters, as opposed to punctuation.

To reproduce:

1. Create a new file.
2. Type some junk made of letters.
3. Ctrl-left
4. View error!

**Comment by ow--** [comment]
Wat. Can't believe that slipped by. I must have always have had a capital word character or, as you said, something else first in the file.

**Comment by JustinPierce** [comment]
One of those "where was my brain?" errors. Happens to the best of us.
